---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: ecommerce
spec:
  encryptedData:
    DB_PASSWORD: AgCeK9tEQE6AG/pEQb/DikASVx3XkUfwFzPgof3DIGYKp86kNLyp1OBRedMQeMzwiC0O3miyRfpDceni44dNyKdDbop/QgnYUNICosCtqvNExe2sn8qxpVmWlnkfMheX9FOt6rWmqH73DGeCp/mf/b0+M3lgbabIdW+pCsgbrLhWLNUoowyk6tcgFgyA3iQLLix3LmEhbzpecr6JBbNAmJuW1owSx/3OrAVAjvKRcLx86A2BF1LNiMwY+2UBcOdtfprCjUa1Pz13bUm6FEdHz53xxz1A1+OGJLfwX3AZ+JilNv+Yz+0YmR0degkoxDwvzFwwGZCBG32NXPEdlz6m/3sDXfwMLIzbOa0zMk6ruPVJYA770oTIeai7hezoKJvkIMVC+cWl17cLF80WrOlUF6oCd8V+1R+6XW3Z5zqbsIy0Xmw7XVde29sjnNinzJHGstfR6fLphGCG+zsdvneQtK74z5x0JZ4qbITFxAyJXuBOzx8oZhgAsdgPGRRw2Jh72qU4CnnoIiP0eFAosgJTvtqZBfnrwb5RNoFVM4J2lZ7YRF793z8Hv+0Nwnh92IzelYB914iWFgxQWSTVofPgPCEwJHAT+WW7XaLDPSaEucUiJ4WMryw7QVJ8n/tZKuHpJaoqbicmXLQhtonwghJArMFZelSRpnwBti8OYasRfcjWSZAxoNG58BK8TJfZYOYW6wZkjCbO846bjyAYxw==
    DB_USER: AgCvCMQ4zKwJXh/lsQVnaQeOEY/jx1d8MuZLliweYCoyJkHJTgPBsS8eQKQcFQsZirhg3r4MPKS7d9kM1l4O24su0tRO+J5Ml2cEC6vB/yta6PkXcdL2wFnDGd9aqCQvg1zQhAM33U0GrmcK7n+yAZaf0xkznADBexc5TbgqlQvHXfokZP8e+dKsaVzvnkO9em9qp+pYtrxZ/g/Dpdei+pvORM0lSQlfK8ars97pUsxTI5+xk7k0W6Aj3G1b2qoMQc1nq7UrmiYHV2R7QD9jSyVxYKSdwEEoqCSgeAX1o/ERR9FyB8l4UxfkkBuZpkIBWBI207swK7iIFTpilAPmf/SXWbpPJmie1Ee4eSppWIkx5Q5oFdrFTooOi5KkRBxEnEQ39mI+EIPvOME7yqtb9kSF2h7RSsyBOem8y1Nz9Lk1MRTyf7S8pGJx7O8O64o31ErgJg+bXLzC72bw9AfV3KvvL6UvZ+dtBlV1lKjo7x6EesyDNkMSugNm1YwmxGqhpx42PHcai9YBVMnJzsQ38T2z7LdFaX+qQ2phZ62XlEkdzkONXotEqOMJ2NPQxCWuk9YQbVPSExf6XfOdggzlTj26FHJ1qnpROC/owVtxjBxcMDQHs2Ppm81++I5qTpkuXMvNbOTw9TC0+iULVo7dAov7UHCxNSKfZ6kZ3gI2qgxein5Qsh6REiDkcw9a2YzEIGymwovQkA==
  template:
    metadata:
      name: db-credentials
      namespace: ecommerce
